version: '2'
services:

  # The Application
  app:
    image: jrszapata/url-shortener-laravel-5.8
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: "php artisan serve --host=0.0.0.0"
    ports:
      - 8000:8000
